# Generated by Django 5.0.1 on 2024-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ratings_sync",
            field=models.IntegerField(default=0),
        ),
    ]
