# Generated by Django 5.0.1 on 2024-05-01 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0004_bookratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="ratings_sync",
        ),
    ]
