# Generated by Django 5.0.1 on 2024-05-01 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0005_remove_book_ratings_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookratings",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
