# Generated by Django 5.0.1 on 2024-05-01 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0006_alter_bookratings_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookRatings",
            new_name="BookRating",
        ),
    ]
