# Generated by Django 5.0.1 on 2024-05-01 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0007_rename_bookratings_bookrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookrating",
            old_name="book",
            new_name="book_id",
        ),
        migrations.RenameField(
            model_name="bookrating",
            old_name="username",
            new_name="user_id",
        ),
    ]
